Debugging messages to debug release
taskcluster/taskcluster-github pull request #102
Opened 2017-01-21 00:55 UTC by owlishDeveloper

Trying to find the reason for intermittent failures of release event handling.

Handlers seem to be nicely equipped with debugging messages, so I focused on server side:

intree.js - check to see if YML is being parsed as expected; catch the taskGroupID for releases.
api.js - check to see if release webhooks arrive and being recognized as such.
exchanges.js - check to see if webhook payload is being parsed.

Also added a bit of clarity so that we instantly could see where the message comes from.

2017-01-21 01:44 UTC, imbstack requested changes
Looks pretty good! Just some minor nits.

2017-01-21 01:44 UTC, imbstack commented on src/api.js
> +      debug('Received release event webhook payload. Processing...');
Maybe add a `// TODO: remove this` here so that we know it's temporary?

2017-01-21 01:44 UTC, imbstack commented on src/intree.js
> +        if (task.task.extra.github.events.some(event => event == 'release')) {
The depth of the dot-access here worries me. Are we sure we won't have an issue with one of these fields not existing or something?

2017-01-21 01:44 UTC, imbstack commented on src/intree.js
> +      if (task.extra.github.events.some(event => event == 'release')) {
Same as below.

2017-01-21 01:53 UTC, owlishDeveloper commented on src/intree.js
> +        if (task.task.extra.github.events.some(event => event == 'release')) {
Well, it comes from [here](https://github.com/taskcluster/taskcluster-github/blob/master/src/intree.js#L101-L104 ) ... I think it should be correct.

2017-01-21 02:00 UTC, owlishDeveloper commented on src/intree.js
> +        if (task.task.extra.github.events.some(event => event == 'release')) {
A seond thought, I can wrap [this whole thing](https://github.com/taskcluster/taskcluster-github/blob/master/src/intree.js#L100-L125) in try-catch block

2017-01-21 02:10 UTC, owlishDeveloper commented
Added `// TO DO` comments

2017-01-21 17:39 UTC, djmitche approved these changes
I'm happy with this once the comments are addressed -- go ahead and push, then we can promote to production.

2017-01-21 17:39 UTC, djmitche commented on src/intree.js
> +        if (task.task.extra.github.events.some(event => event == 'release')) {
It's usually better to be safe than sorry with temporary debugging stuff, so I like the try/catch block.

2017-01-22 00:00 UTC, djmitche commented on src/intree.js
> +      if (task.extra.github.events.some(event => event == 'release')) {
don't forget this one ^^

2017-01-22 00:13 UTC, owlishDeveloper commented
Oh dear... That's messy even by my standards! I'm closing this for now; besides, I think I noticed an error in my code there

2017-01-22 00:13 UTC, closed without merging

2017-01-22 00:31 UTC, owlishDeveloper commented on src/intree.js
> +      if (task.extra.github.events.some(event => event == 'release')) {
You mean add it to try-catch? I didn't :) However, before messing up commits again, I deployed the thing, and it appears there may be something wrong with parsing YML. I'll look more closely later.

2017-01-22 16:05 UTC, djmitche commented
Yeah, it looks like you merged pete's changes, too?

2017-01-22 16:13 UTC, owlishDeveloper commented
Yep 😜. It's all because on my local repo, I didn't make a separate branch for this, and I also don't keep my master up-to-date :( What will happen when this PR will get merged - this mess will remain, won't it? Is there a way of repairing this?

2017-01-22 16:17 UTC, djmitche commented
A rebase onto an updated master should be able to fix it.  However, if you've already merged things to master, then it may be too late :(

2017-01-22 16:18 UTC, djmitche commented
*dustin actually looks at master*

OK, nothing got merged so that's not an issue .
```
git fetch upstream
git rebase -i upstream/master
```
should do the trick -- just drop any commits that aren't about adding debug info (and maybe squash those which are),

2017-01-22 16:23 UTC, owlishDeveloper commented
Yeah, I meant my local master (the poor thing just doesn't seem to be able to get a nice quiet life on my computer).

Ok, I'll try that rebase, thank you!

2017-01-22 16:46 UTC, owlishDeveloper commented
Yay! It worked, thank you Dustin!!