Update public api
taskcluster/taskcluster-github pull request #193
Opened 2017-05-09 21:46 UTC by imbstack

This is my idea for rearranging our http endpoints and library function names a bit to align more with the resource mapping we can have in addition to general flexibility.

Let me know what you think!

2017-05-09 22:03 UTC, owlishDeveloper commented on src/api.js
> +  route: '/repository/:owner/:repo/:branch',
It will not be confusing, will it? From such a general name, I guess we plan to make more APIs that have `repository/` in their route?

2017-05-09 23:35 UTC, djmitche requested changes
Minor changes, but thanks for this cleanup!

2017-05-09 23:35 UTC, djmitche commented on src/api.js
> +    'Note: This may be a redirect rather than a direct link.',
Isn't it always a redirect?

2017-05-09 23:35 UTC, djmitche commented on src/api.js
> +  route: '/repository/:owner/:repo/:branch',
All of the API methods start with `/repository` :)

But you're right - it seems like it should be `/repository/:owner/:repo/:branch/latest` or something like that, to parallel the `badge.svg` route.

2017-05-10 00:08 UTC, owlishDeveloper approved these changes

2017-05-10 14:17 UTC, djmitche approved these changes

2017-05-10 16:36 UTC, merged