Fix logic of exclude branches
taskcluster/taskcluster-github pull request #234
Opened 2018-03-22 13:19 UTC by imbstack

This adds some tests and changes the logic of exclude branches a bit. [Bug 1433506](https://bugzilla.mozilla.org/show_bug.cgi?id=1433506)

2018-03-22 16:33 UTC, djmitche requested changes

2018-03-22 16:33 UTC, djmitche commented on src/intree.js
>          let branch = payload.details['event.base.repo.branch'];
can we call this `includeBranches` for parallelism

2018-03-22 16:33 UTC, djmitche commented on src/intree.js
> +            return included && !excluded;
isn't this option not allowed now?

2018-03-26 13:28 UTC, staktrace commented
@djmitche Looks like the patch was updated, could you re-review? Thanks!

2018-03-26 18:48 UTC, djmitche requested changes

2018-03-26 18:48 UTC, djmitche commented on src/intree.js
> +          }
I think the error message here is incorrect.  The condition here is that there is both a `branches` and an `excludeBranches`.  The README suggests this situation is allowed (although I don't know what that would mean -- if a branch isn't on either list, is it included or excluded?).

I think when we talked about this briefly, we decided that this case is not allowed -- you must use no more than one of `branches` or `excludeBranches`.  Then there's no concern with the same branch appearing in both lists.

2018-04-03 17:57 UTC, djmitche approved these changes

2018-04-03 18:01 UTC, merged