Bug 1501005 - shut down monitoring when finished syncing
taskcluster/taskcluster-github pull request #289
Opened 2018-10-22 21:30 UTC by djmitche

This fixes the hangs, which occur because tc-lib-monitor is running on an interval (`setInterval`) and node is sticking around to service that.

2018-10-22 21:55 UTC, owlishDeveloper approved these changes

2018-10-22 21:56 UTC, owlishDeveloper requested changes

2018-10-22 21:56 UTC, owlishDeveloper commented on src/main.js
> +      monitor.stopResourceMonitoring();
oh, this probably needs the `monitor` to passed in

2018-10-23 03:21 UTC, djmitche commented on src/main.js
> +      monitor.stopResourceMonitoring();
Ack, good catch.  I made this change on a running pod to test it and then failed to copy out all of my changes.

2018-10-23 03:31 UTC, djmitche commented
ok, checks pass now :)

2018-10-23 16:12 UTC, owlishDeveloper approved these changes

2018-10-23 16:13 UTC, merged